### ISSUE TITLE
multiauth installed, driver not used: Error 500 when accessing jauthdb_admin/default/view?j_user_login

### ISSUE THREAD

**Issue by rldhont** [jelix/multiauth-module#5]
```
Call to undefined method ldapdaoAuthDriver::getProviderForLogin()	/srv/lizmap-modules/multiauth-module/multiauth/classes/multiauth.listener.php	23
```

The config is:
```
[modules]
multiauth.access=1

[coordplugin_auth]
driver=ldapdao
```

Same issue when `multiauth.access=0`

**Comment by laurentj** [comment]
you set `driver=ldapdao`, instead of `driver=multiauth`. This is why there is the error.

If you want to deactivate the multiauth module, you should set access=0, and run the installer, remove the content of temp/.
