### ISSUE TITLE
Compatibilité Multiauth - Lizmap web client 3.6.1 ? 

### ISSUE THREAD

**Issue by relaire** [jelix/multiauth-module#8]
Bonjour 
J'ai l'habitude d'utiliser le module MultiAuth sur une serveur Lizmap (v3.5).
Je fais des tests sur un nouveau serveur lizmap (3.6.1) et je n'arrive plus a activer le module MultiAuth
Quand je remplace 
;driver=ldapdao -> _driver=multiauth_

J'obtiens une erreur 500 à l'authentification, et dans le fichier log 
 _Class 'Jelix\MultiAuth\ProviderAbstract' not found	/var/www/lizmap-web-client-3.6.1/lizmap/lizmap-modules/multiauth/plugins/multiauth/ldap/ldap.multiauth.php	21_

La configuration LDAP ayant pas mal évolué dans cette nouvelle version de Lizmap, ma question est de savoir si le module Multiauth est toujours compatible.
Merci
Renaud

**Comment by laurentj** [comment]
Bonjour

* Avez-vous installé la dernière version 1.2.0 de MultiAuth ?
* Avez vous lancé les commandes suivantes ?

```bash
cd lizmap/install/
php configurator.php multiauth
php installer.php
./clean_vartmp.sh
./set_rights.sh
```

**Comment by xavyeah39** [comment]
Bonjour @laurentj,

Oui nous avons bien veiller à : 
- mettre à jour Lizmap en 3.6.2 + repris et contrôlé nos conf
- réinstallé le module multiauth avec Composer
- lancé les commandes ci-dessus 

Mais cette même erreur persiste dans les logs lizmap : 
```
Class 'Jelix\MultiAuth\ProviderAbstract' not found      /var/www/lizmap-web-client-3.6.2/lizmap/my-packages/vendor/jelix/multiauth-module/multiauth/plugins/multiauth/ldap/ldap.multiauth.php 21
```

Merci par avance.

**Comment by josemvm** [comment]
`[error] The module jauth is in conflict with jcommunity. Only one of them can be installed.
Installation/upgrade is aborted`

**Comment by laurentj** [comment]
J'ai effectué des corrections dans le module et dans Lizmap. Le problème sera corrigé dans Lizmap 3.6.3 qui sort cette semaine.

I made some patches into the module and into Lizmap. The problem will be fixed into Lizmap 3.6.3 which will be released this week
